server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:auth-service}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:bank_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bank_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:bank_password}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL:false}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    properties:
      security.protocol: ${SPRING_KAFKA_SECURITY_PROTOCOL:PLAINTEXT}

app:
  kafka:
    topics:
      auth-events: ${AUTH_EVENTS_TOPIC:auth.events.v1}
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}

auth:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-to-at-least-32-bytes-long}
    registration-expiration-minutes: ${AUTH_JWT_REGISTRATION_EXPIRATION_MINUTES:10}
    access-expiration-minutes: ${AUTH_JWT_ACCESS_EXPIRATION_MINUTES:15}
    refresh-expiration-minutes: ${AUTH_JWT_REFRESH_EXPIRATION_MINUTES:43200}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
